config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'blogs#index'
  resources :blogs
  resources :users,only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :start_time, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :ion?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def ion?
    Rails.env.ion?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials[:basic_auth][:user] &&
      password == Rails.application.credentials[:basic_auth][:pass]
    end
  end

  def configure_permitted_parameters
    added_attrs = [ :name,
                    :email,
                    :password,
                    :password_confirmation,
                  ]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    Blog.create(blog_parameter)
    redirect_to blogs_path
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_parameter)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  private

  def blog_parameter
    params.require(:blog).permit(:title, :content, :start_time).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @blog = current_user.blogs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/blog/_new.html.haml
= form_with(model: @blog, local: true) do |form|
  .title
    = form.label :title
    = form.text_field :title
  .time
    = form.label :start_time
    = form.datetime_select :start_time
  .content
    = form.label :content
    = form.text_field :content
  .submit
    = form.submit

app/views/blogs/edit.html.haml
= render "blogs/blog/new"

app/views/blogs/index.html.haml
%p#notice= notice
%table
  %thead
    %tr
      %th タイトル
      %th 時間
      %th{:colspan => "3"}
  %tbody
    - @blogs.each do |blog|
      %tr
        %td= blog.title
        %td= blog.start_time.strftime("%Y-%m-%d %H:%M")
        %td= link_to '表示', blog
      - if user_signed_in? && current_user.id == blog.user_id
        %td= link_to '変更する', edit_blog_path(blog.id)
        %td= link_to '消去',blog_path(blog.id), method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'カレンダー記載', new_blog_path
= month_calendar events: @blogs do |date, blogs|
  = date.day
  - blogs.each do |blog|
    %div
      = link_to blog.title, blog

app/views/blogs/new.html.haml
= render "blogs/blog/new"

app/views/blogs/show.html.haml
%p#notice= notice
%p
  %strong タイトル
  = @blog.title
%p
  %strong 時間
  = @blog.start_time.strftime("%Y-%m-%d %H:%M")
%p
  %strong 内容
  = @blog.content
= link_to 'Edit', edit_blog_path(@blog)
|
= link_to 'Back', blogs_path

app/views/contents/_header.html.haml
.header
  .header__bar
    -if user_signed_in?
      .user_nav
        %ul
          .user__info
          %li
            -# =link_to "マイページ", "/users/#{current_user.id}"
            =link_to "ログアウト", destroy_user_session_path, method: :delete 
        = link_to "投稿する", new_blog_path, class: "post"
    -else
      .grid-6
        = link_to "ログイン", new_user_session_path, class: "post"
        = link_to "新規会員登録", new_user_registration_path, class: "post"

  %h1 カレンダー共有アプリ

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CarendarAPP
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'contents/header'
    = yield

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        = content_tag :tr, class: calendar.tr_classes_for(week) do
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    - if calendar.number_of_weeks == 1
      %span.calendar-title
        Week #{calendar.week_number}
    - else
      %span.calendar-title
        Week #{calendar.week_number} - #{calendar.end_week}
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block)
                - capture_haml(day, sorted_events.fetch(day, []), &passed_block)
              - else
                - passed_block.call day, sorted_events.fetch(day, [])

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :public_uid
    = f.text_field :public_uid
  .actions
    = f.submit 'Save'